apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langflow-runtime.databaseSecretName" . }}
  labels:
    {{- include "langflow-runtime.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.url | quote }}
